# Generated by Django 5.0.3 on 2024-03-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendsetteruser',
            options={'verbose_name': 'User'},
        ),
    ]
