# Generated by Django 5.0.3 on 2024-04-10 13:18

import TrendSetter.articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_age_profile_trading_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='trading_from',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/anonymous-user.webp', upload_to='profile_images/', validators=[TrendSetter.articles.validators.image_size_validator]),
        ),
    ]
