# Generated by Django 5.0.3 on 2024-04-11 07:02

import TrendSetter.articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_trading_from_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images/', validators=[TrendSetter.articles.validators.image_size_validator]),
        ),
    ]
