# Generated by Django 5.0.3 on 2024-03-28 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='education_article_gallery/')),
            ],
        ),
        migrations.AlterField(
            model_name='educationarticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='education_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationarticle',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='articles.gallery'),
        ),
    ]
