# Generated by Django 5.0.3 on 2024-03-30 06:34

import TrendSetter.articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_gallery_alter_educationarticle_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationarticle',
            name='image',
            field=models.ImageField(upload_to='education_articles/', validators=[TrendSetter.articles.validators.image_size_validator]),
        ),
    ]
