# Generated by Django 5.0.3 on 2024-04-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_educationalarticle_gallery_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalarticle',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
