# Generated by Django 5.0.3 on 2024-04-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_educationalarticle_author_name_alter_comment_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
