# Generated by Django 5.0.3 on 2024-04-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_ideas', '0003_tradeidea_views_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeidea',
            name='category',
            field=models.CharField(choices=[('forex', 'Forex'), ('commodites', 'Commodities'), ('indicies', 'Indicies'), ('stocks', 'Stocks'), ('crypto', 'Crypto')], default='Forex', max_length=20),
        ),
    ]
