# Generated by Django 5.0.3 on 2024-04-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_ideas', '0004_tradeidea_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeidea',
            name='category',
            field=models.CharField(choices=[('Forex', 'Forex'), ('Crypto', 'Crypto'), ('Indicies', 'Indicies'), ('Stocks', 'Stocks'), ('Commodites', 'Commodities'), ('Other', 'Other')], default='Forex', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeidea',
            name='symbol',
            field=models.CharField(choices=[('FX:EURUSD', 'EURUSD'), ('FX:GBPUSD', 'GBPUSD'), ('FX:USDCHF', 'USDCHF'), ('FX:USDJPY', 'USDJPY'), ('FX:EURJPY', 'EURJPY'), ('FX:AUDUSD', 'AUDUSD'), ('COINBASE:BTCUSD', 'BTCUSD'), ('COINBASE:ETHUSD', 'ETHUSD'), ('AMEX:SPY', 'SPY'), ('NASDAQ:NDX', 'NASDAQ'), ('NASDAQ:AAPL', 'AAPL'), ('NASDAQ:TSLA', 'TSLA'), ('NASDAQ:NVDA', 'NVDA'), ('NASDAQ:AMZN', 'AMZN'), ('SAXO:XAUUSD', 'GOLD'), ('SAXO:XAGUSD', 'SILVER'), ('Other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='tradeidea',
            name='timeframe',
            field=models.CharField(choices=[('15M', '15M'), ('30M', '30M'), ('1H', '1H'), ('4H', '4H'), ('1D', '1D'), ('1W', '1W'), ('1M', '1M')], max_length=20),
        ),
    ]
